repos:
  -
    repo: https://github.com/pycqa/flake8
    rev: '6.1.0'
    hooks:
      -
        id: flake8
        additional_dependencies:
          - flake8-docstrings
          - flake8-sfs
        args: [--max-line-length=120, --extend-ignore=SFS101 D401 SFS301]

  -
    repo: https://github.com/PyCQA/isort
    rev: '5.12.0'
    hooks:
      -
        id: isort

#  - repo: local
#    hooks:
#      -
#        id: pytest
#        name: pytest
#        entry: cd tests pytest
#        language: system
#        pass_filenames: false
#        always_run: true

  -
    repo: local
    hooks:
      -
        id: docs
        name: docs
        entry: /bin/bash gen_docs.sh
        language: system
        pass_filenames: false
        always_run: true
